### ISSUE TITLE
1.8.0 breaks sender:connect plugin

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#143]
We have a custom plugin for DKIM logic and since the upgrade to 1.8.0 does not work anymore.

Code:
```
    app.addHook('sender:connect', (delivery, options, next) => {
        delivery.headers.remove("X-Custom....");
```

Error i see in the log:
```
May 22 08:19:44 z zone-mta: /usr/local/zonemta/plugins/custom.js:15
May 22 08:19:44 z zone-mta:         delivery.headers.remove("X-Custom....);
May 22 08:19:44 z zone-mta:                         ^
May 22 08:19:44 z zone-mta:

May 22 08:19:44 z zone-mta: TypeError: Cannot read property 'remove' of undefined
May 22 08:19:44 z zone-mta:     at Object.app.addHook [as action] (/usr/local/zonemta/plugins/custom.js:15:25)
May 22 08:19:44 z zone-mta:     at Immediate.checkNext (/usr/local/zonemta/node_modules/zone-mta/lib/plugin-handler.js:420:18)
May 22 08:19:44 z zone-mta:     at runCallback (timers.js:672:20)
May 22 08:19:44 z zone-mta:     at tryOnImmediate (timers.js:645:5)
May 22 08:19:44 z zone-mta:     at processImmediate [as _immediateCallback] (timers.js:617:5)
May 22 08:19:44 z zone-mta: ERR! Child/default/1256 [1889b77278f421a1e506] Sender process for default exited with 1
```

**Comment by andris9** [comment]
Could you try using v1.8.1, I reverted the hook options

**Comment by dazoot** [comment]
Now i see:
```
May 22 17:04:34 z zone-mta: ERR! Sender/gmail/27557[5] 16388615362000d8ab.001 ERRCONNECT domain=gmail.com error=Cannot read property 'name' of undefined
```

**Comment by andris9** [comment]
Is this error coming from your custom plugin? Can't really trigger it myself

**Comment by dazoot** [comment]
I don't have in any plugins `name` so i think it's not plugin related.

**Comment by dazoot** [comment]
It seems the error occurs in:
```
mxConnect(mxOptions, (err, mx) => {
```

**Comment by dazoot** [comment]
Can it be related to the fact that we have some zones which send via smtp auth.

Ex:
```
port = 587
host = "smtp.gmail.com"

[default.auth]
```

**Comment by andris9** [comment]
Using `host` option seemed to be broken, I fixed it in v1.8.4. Using `recipientDomains` should not affect anything, I use it myself and I have no issues.

**Comment by dazoot** [comment]
I still get undefined error after upgrade to 1.8.4.

```
    "messages": [
        {
            "deferred": {
                "count": 13,
                "first": 1527228262630,
                "last": 1527237887019,
                "log": null,
                "next": 1527239087019,
                "response": "Cannot read property 'name' of undefined"
            },
```

As soon as i remove recipientDomains from all zones, error is gone.

`delivery.zoneAddress.name,` this sometimes is null in the debug i've tried.

**Comment by dazoot** [comment]
Hmm. Now even after i remove `recipientDomains` i still get the error.

```
May 25 11:50:15 z zone-mta: ERR! Sender/z1/13978[1] 16395eac9310000119.001 ERRCONNECT domain=yahoo.com error=Cannot read property 'name' of undefined
```

**Comment by dazoot** [comment]
I did some debug in sender.js:
```
log.info(this.logName, "zoneAddress = %s", delivery.zoneAddress);
```

```
May 25 11:53:31 z zone-mta: info Sender/z1/15037[3] zoneAddress = undefined
May 25 11:53:31 z zone-mta: ERR! Sender/z1/15037[3] 163960038080000119.001 ERRCONNECT domain=yahoo.com error=Cannot read property 'name' of undefined
May 25 11:53:31 z zone-mta: info Sender/z1/15037[3] 163960038080000119.001 DEFERRED[connection] from=....tazi.eu to=test@yahoo.com src=IP mx=yahoo.com id=<20180525063306.11085.1775.594783.287825739.nl@email> (Cannot read property 'name' of undefined)
```

**Comment by andris9** [comment]
Do you also use the built-in dkim plugin? This might have caused something like this. I upgraded zone-mta to 1.8.5 with a fix.

**Comment by dazoot** [comment]
All works ok now. Thanks.
